version: "3.7"
services:
  ngnix:
    image: nginx:1.19.5
    volumes:
      - /home/nginx_setting/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
    networks:
      - network
    ports:
      - 80:80

  django_container_gunicorn:
    image: django_test_image:1
    networks:
      - network
    volumes:
      - static-volume:/home/dev/BACKEND/staticfiles
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
      - EMAIL_HOST_PASSWORD
      - TEAM_PW

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - /home/mariadb_setting/my.cnf:/etc/mysql/my.cnf
      - maria-database:/var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    command: --lower_case_table_names=0
    environment:
      MYSQL_DATABASE: poppymail_db
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

networks:
  network:

volumes:
  maria-database:
  static-volume:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
  EMAIL_HOST_PASSWORD:
    external: true
  TEAM_PW:
    external: true